<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../RoboTransfer.Core/RoboTransfer.Core.csproj" /><ProjectReference Include="../RoboTransfer.Robocopy/RoboTransfer.Robocopy.csproj" /><ProjectReference Include="../RoboTransfer.Usmt/RoboTransfer.Usmt.csproj" /><PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" /><PackageReference Include="System.Security.Principal.Windows" Version="6.0.1" /></ItemGroup></Project>
